from django.conf import settings

IMGPROXY_BASE_URL = getattr(
    settings, "IMGPROXY_BASE_URL", "http://localhost:8080"
).rstrip("/")
IMGPROXY_ONLY_PRESETS = getattr(settings, "IMGPROXY_ONLY_PRESETS", False)
IMGPROXY_ARGUMENTS_SEPARATOR = getattr(settings, "IMGPROXY_ARGUMENTS_SEPARATOR", ":")
IMGPROXY_KEY = bytes.fromhex(getattr(settings, "IMGPROXY_KEY", ""))
IMGPROXY_SALT = bytes.fromhex(getattr(settings, "IMGPROXY_SALT", ""))
IMGPROXY_SIGN_URL = bool(IMGPROXY_KEY) and bool(IMGPROXY_SALT)
IMGPROXY_NO_SIGNATURE_SEGMENT = getattr(
    settings, "IMGPROXY_NO_SIGNATURE_SEGMENT", "unsafe"
)
IMGPROXY_PERCENT_ENCODED_PROCESSING_OPTIONS = getattr(
    settings, "IMGPROXY_PERCENT_ENCODED_PROCESSING_OPTIONS", {"filename", "fn"}
)
IMGPROXY_SOURCE_URL_PREFIX = getattr(settings, "IMGPROXY_SOURCE_URL_PREFIX", "")
IMGPROXY_PERCENT_ENCODE_SOURCE_URL = getattr(
    settings, "IMGPROXY_PERCENT_ENCODE_SOURCE_URL", True
)
IMGPROXY_PERCENT_ENCODE_SOURCE_URL_SAFE_CHARACTERS = "/"
IMGPROXY_BASE64_ENCODE_SOURCE_URL = getattr(
    settings, "IMGPROXY_BASE64_ENCODE_SOURCE_URL", False
)
IMGPROXY_IMAGEFIELD_URL_TTL = getattr(settings, "IMGPROXY_IMAGEFIELD_URL_TTL", 0)
